---
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [-f, requirements.txt, -o, requirements.txt]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
